<?php

use Illuminate\Database\Seeder;
use App\Service;
class ServicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Servise::create(['shop_id' => 2,'item_id' => 1,'price' => '¥3000']);
      Servise::create(['shop_id' => 2,'item_id' => 2,'price' => '¥2500']);
      Servise::create(['shop_id' => 2,'item_id' => 3,'price' => '¥4000']);
      Servise::create(['shop_id' => 2,'item_id' => 4,'price' => '¥1000']);
      Servise::create(['shop_id' => 2,'item_id' => 5,'price' => '¥300']);
      Servise::create(['shop_id' => 2,'item_id' => 6,'price' => '¥2000']);
      Servise::create(['shop_id' => 2,'item_id' => 7,'price' => '¥3000']);
      Servise::create(['shop_id' => 2,'item_id' => 8,'price' => '¥10000']);
      Servise::create(['shop_id' => 2,'item_id' => 9,'price' => '¥2000']);
      Servise::create(['shop_id' => 2,'item_id' => 10,'price' => '¥1000']);
      Servise::create(['shop_id' => 2,'item_id' => 11,'price' => '¥500']);
      Servise::create(['shop_id' => 2,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 2,'item_id' => 13,'price' => '¥500']);
      Servise::create(['shop_id' => 2,'item_id' => 14,'price' => '¥500~']);
      Servise::create(['shop_id' => 2,'item_id' => 15,'price' => '¥2500']);
      Servise::create(['shop_id' => 2,'item_id' => 16,'price' => '¥500']);
      Servise::create(['shop_id' => 3,'item_id' => 29,'price' => '¥10000']);
      Servise::create(['shop_id' => 3,'item_id' => 30,'price' => '¥3000']);
      Servise::create(['shop_id' => 3,'item_id' => 31,'price' => '¥5000']);
      Servise::create(['shop_id' => 4,'item_id' => 1,'price' => '¥500']);
      Servise::create(['shop_id' => 4,'item_id' => 2,'price' => '¥500']);
      Servise::create(['shop_id' => 4,'item_id' => 3,'price' => '¥4000']);
      Servise::create(['shop_id' => 4,'item_id' => 4,'price' => '¥1500']);
      Servise::create(['shop_id' => 4,'item_id' => 5,'price' => '¥300']);
      Servise::create(['shop_id' => 4,'item_id' => 6,'price' => '¥2000']);
      Servise::create(['shop_id' => 4,'item_id' => 7,'price' => '¥3000']);
      Servise::create(['shop_id' => 4,'item_id' => 8,'price' => '¥8000']);
      Servise::create(['shop_id' => 4,'item_id' => 9,'price' => '¥1800']);
      Servise::create(['shop_id' => 4,'item_id' => 10,'price' => '¥2000']);
      Servise::create(['shop_id' => 4,'item_id' => 11,'price' => '¥500']);
      Servise::create(['shop_id' => 4,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 4,'item_id' => 13,'price' => '¥500']);
      Servise::create(['shop_id' => 4,'item_id' => 14,'price' => '¥300~']);
      Servise::create(['shop_id' => 4,'item_id' => 15,'price' => '¥2300']);
      Servise::create(['shop_id' => 4,'item_id' => 16,'price' => '¥500']);
      Servise::create(['shop_id' => 5,'item_id' => 1,'price' => '¥300']);
      Servise::create(['shop_id' => 5,'item_id' => 2,'price' => '¥400']);
      Servise::create(['shop_id' => 5,'item_id' => 3,'price' => '¥4500']);
      Servise::create(['shop_id' => 5,'item_id' => 4,'price' => '¥1500']);
      Servise::create(['shop_id' => 5,'item_id' => 5,'price' => '¥400']);
      Servise::create(['shop_id' => 5,'item_id' => 6,'price' => '¥1600']);
      Servise::create(['shop_id' => 5,'item_id' => 7,'price' => '¥4000']);
      Servise::create(['shop_id' => 5,'item_id' => 8,'price' => '¥9000']);
      Servise::create(['shop_id' => 5,'item_id' => 9,'price' => '¥1800']);
      Servise::create(['shop_id' => 5,'item_id' => 10,'price' => '¥2300']);
      Servise::create(['shop_id' => 5,'item_id' => 11,'price' => '¥600']);
      Servise::create(['shop_id' => 5,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 5,'item_id' => 13,'price' => '¥400']);
      Servise::create(['shop_id' => 5,'item_id' => 14,'price' => '¥400~']);
      Servise::create(['shop_id' => 5,'item_id' => 15,'price' => '¥2100']);
      Servise::create(['shop_id' => 5,'item_id' => 16,'price' => '¥600']);
      Servise::create(['shop_id' => 6,'item_id' => 1,'price' => '¥300']);
      Servise::create(['shop_id' => 6,'item_id' => 2,'price' => '¥400']);
      Servise::create(['shop_id' => 6,'item_id' => 3,'price' => '¥3500']);
      Servise::create(['shop_id' => 6,'item_id' => 4,'price' => '¥2300']);
      Servise::create(['shop_id' => 6,'item_id' => 5,'price' => '¥600']);
      Servise::create(['shop_id' => 6,'item_id' => 6,'price' => '¥4000']);
      Servise::create(['shop_id' => 6,'item_id' => 7,'price' => '¥4000']);
      Servise::create(['shop_id' => 6,'item_id' => 8,'price' => '¥9000']);
      Servise::create(['shop_id' => 6,'item_id' => 9,'price' => '¥2000']);
      Servise::create(['shop_id' => 6,'item_id' => 10,'price' => '¥3000']);
      Servise::create(['shop_id' => 6,'item_id' => 11,'price' => '¥600']);
      Servise::create(['shop_id' => 6,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 6,'item_id' => 13,'price' => '¥600']);
      Servise::create(['shop_id' => 6,'item_id' => 14,'price' => '¥500~']);
      Servise::create(['shop_id' => 6,'item_id' => 15,'price' => '¥2500']);
      Servise::create(['shop_id' => 6,'item_id' => 16,'price' => '¥500']);
      Servise::create(['shop_id' => 7,'item_id' => 41,'price' => '¥500']);
      Servise::create(['shop_id' => 7,'item_id' => 42,'price' => '¥300']);
      Servise::create(['shop_id' => 7,'item_id' => 43,'price' => '¥10000']);
      Servise::create(['shop_id' => 7,'item_id' => 44,'price' => '¥1000']);
      Servise::create(['shop_id' => 7,'item_id' => 45,'price' => '¥500']);
      Servise::create(['shop_id' => 7,'item_id' => 46,'price' => '¥2000']);
      Servise::create(['shop_id' => 7,'item_id' => 47,'price' => '¥1000']);
      Servise::create(['shop_id' => 7,'item_id' => 48,'price' => '¥15000']);
      Servise::create(['shop_id' => 7,'item_id' => 49,'price' => '¥2000']);
      Servise::create(['shop_id' => 7,'item_id' => 50,'price' => '¥1000']);
      Servise::create(['shop_id' => 7,'item_id' => 51,'price' => '¥400']);
      Servise::create(['shop_id' => 7,'item_id' => 52,'price' => '要相談']);
      Servise::create(['shop_id' => 7,'item_id' => 53,'price' => '¥500']);
      Servise::create(['shop_id' => 7,'item_id' => 54,'price' => '要相談']);
      Servise::create(['shop_id' => 8,'item_id' => 1,'price' => '¥800']);
      Servise::create(['shop_id' => 8,'item_id' => 2,'price' => '¥500']);
      Servise::create(['shop_id' => 8,'item_id' => 3,'price' => '¥10000']);
      Servise::create(['shop_id' => 8,'item_id' => 4,'price' => '¥1000']);
      Servise::create(['shop_id' => 8,'item_id' => 5,'price' => '¥300']);
      Servise::create(['shop_id' => 8,'item_id' => 6,'price' => '¥1800']);
      Servise::create(['shop_id' => 8,'item_id' => 7,'price' => '¥3000']);
      Servise::create(['shop_id' => 8,'item_id' => 8,'price' => '¥15000']);
      Servise::create(['shop_id' => 8,'item_id' => 9,'price' => '¥2000']);
      Servise::create(['shop_id' => 8,'item_id' => 10,'price' => '¥1000']);
      Servise::create(['shop_id' => 8,'item_id' => 11,'price' => '¥600']);
      Servise::create(['shop_id' => 8,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 8,'item_id' => 13,'price' => '¥700']);
      Servise::create(['shop_id' => 8,'item_id' => 14,'price' => '¥600~']);
      Servise::create(['shop_id' => 8,'item_id' => 15,'price' => '¥2500']);
      Servise::create(['shop_id' => 8,'item_id' => 16,'price' => '¥500']);
      Servise::create(['shop_id' => 8,'item_id' => 17,'price' => '¥12000']);
      Servise::create(['shop_id' => 8,'item_id' => 18,'price' => '¥2000']);
      Servise::create(['shop_id' => 8,'item_id' => 19,'price' => '¥2000']);
      Servise::create(['shop_id' => 8,'item_id' => 20,'price' => '¥2100']);
      Servise::create(['shop_id' => 8,'item_id' => 21,'price' => '¥3000']);
      Servise::create(['shop_id' => 8,'item_id' => 23,'price' => '¥3500']);
      Servise::create(['shop_id' => 8,'item_id' => 24,'price' => '¥3500']);
      Servise::create(['shop_id' => 8,'item_id' => 25,'price' => '¥1500']);
      Servise::create(['shop_id' => 8,'item_id' => 26,'price' => '要相談']);
      Servise::create(['shop_id' => 8,'item_id' => 27,'price' => '¥1000']);
      Servise::create(['shop_id' => 8,'item_id' => 28,'price' => '¥1000']);
      Servise::create(['shop_id' => 9,'item_id' => 1,'price' => '¥2500']);
      Servise::create(['shop_id' => 9,'item_id' => 2,'price' => '¥2800']);
      Servise::create(['shop_id' => 9,'item_id' => 3,'price' => '¥3500']);
      Servise::create(['shop_id' => 9,'item_id' => 4,'price' => '¥900']);
      Servise::create(['shop_id' => 9,'item_id' => 5,'price' => '¥200']);
      Servise::create(['shop_id' => 9,'item_id' => 6,'price' => '¥1800']);
      Servise::create(['shop_id' => 9,'item_id' => 7,'price' => '¥2800']);
      Servise::create(['shop_id' => 9,'item_id' => 8,'price' => '¥10000']);
      Servise::create(['shop_id' => 9,'item_id' => 9,'price' => '¥3000']);
      Servise::create(['shop_id' => 9,'item_id' => 10,'price' => '¥1400']);
      Servise::create(['shop_id' => 9,'item_id' => 11,'price' => '¥600']);
      Servise::create(['shop_id' => 9,'item_id' => 12,'price' => '要相談']);
      Servise::create(['shop_id' => 9,'item_id' => 13,'price' => '¥600']);
      Servise::create(['shop_id' => 9,'item_id' => 14,'price' => '¥600~']);
      Servise::create(['shop_id' => 9,'item_id' => 15,'price' => '¥2300']);
      Servise::create(['shop_id' => 9,'item_id' => 16,'price' => '¥500']);
      Servise::create(['shop_id' => 9,'item_id' => 17,'price' => '¥12000']);
      Servise::create(['shop_id' => 9,'item_id' => 18,'price' => '¥2000']);
      Servise::create(['shop_id' => 9,'item_id' => 19,'price' => '¥2000']);
      Servise::create(['shop_id' => 9,'item_id' => 20,'price' => '¥2100']);
      Servise::create(['shop_id' => 9,'item_id' => 21,'price' => '¥3000']);
      Servise::create(['shop_id' => 9,'item_id' => 23,'price' => '¥3500']);
      Servise::create(['shop_id' => 9,'item_id' => 24,'price' => '¥3500']);
      Servise::create(['shop_id' => 9,'item_id' => 25,'price' => '¥1500']);
      Servise::create(['shop_id' => 9,'item_id' => 26,'price' => '要相談']);
      Servise::create(['shop_id' => 9,'item_id' => 27,'price' => '¥1000']);
      Servise::create(['shop_id' => 9,'item_id' => 28,'price' => '¥1000']);
    }
}